version: '3'

services:
  guest:
    container_name: lab-sys-guest
    image: lab-sys-guest:latest
    build:
      context: ../
      dockerfile: container/Dockerfile-Guest
    ports:
      - 8080:8080
  admin:
    container_name: lab-sys-admin
    image: lab-sys-admin:latest
    build:
      context: ../
      dockerfile: container/Dockerfile-Admin
    ports:
      - 8081:8081
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  oss:
    container_name: minio
    image: bitnami/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9090:9090
      - 9091:9091
  cache:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
      - 16379:16379