server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 本地
    url: jdbc:mysql://localhost:3306/web
    # compose
    # url: jdbc:mysql://mysql:3306/web
    # 作者compose
    # url: jdbc:mysql://10.88.0.7:3306/web
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
minio:
  endpoint: 1
  bucket-name: 2
  access-key: 3
  secret-key: 4