server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/web
    url: jdbc:mysql://10.88.0.7:3306/web
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 205MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 本地跑直接删除
  data:
    redis:
      host: 10.88.0.9
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
minio:
  # endpoint: http://localhost:9000
  endpoint: http://10.88.0.8:9000
  bucket-name: web
  access-key: minioadmin
  secret-key: minioadmin
resilience4j:
  ratelimiter:
    metrics:
      enabled: true
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 1s
        timeout-duration: 1